module.exports.descriptors = [
    'Erdei',
    'Ősi',
    'Ásványos',
    'Zúgó',
    'Kascade',
    'Zuhanó',
    'Csendes',
    'Szőlőtő',
    'Békakoncert',
    'Juhar',
    'Ködös',
    'Őz',
    'Grizzly',
    'Óceán',
    'Tenger',
    'Égbolt',
    'Poros',
    'Gyémánt'
];

module.exports.places = [
    'Síkság',
    'Falucska',
    'Kanyon',
    'Tó',
    'Csoporttábor',
    'Lovastábor',
    'Kísértetváros',
    'Tábor',
    'Szétszórt Tábor',
    'Vadon',
    'Folyó',
    'Patak',
    'Patakos',
    'Öböl',
    'Forrás',
    'Part',
    'Homok',
    'Mulanú tábor',
    'Vadásztábor',
    'Szirt',
    'Völgy'
];
